In [1]:
import numpy as np

In [15]:
arr = np.array([1,2,3])
arr = arr.astype(np.int8)
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)
print(type(arr))

(3,)
3
1
int8
<class 'numpy.ndarray'>


In [27]:
#zero
arr1 = np.zeros((2,3), dtype=np.int64)
#print(arr1)

arr2 = np.ones((3,2))
# print(arr2)

arr3 = np.empty((2,2),dtype=np.int64)
# print(arr3)

arr4 = np.full((2,3), np.inf)
print(arr4)

[[inf inf inf]
 [inf inf inf]]


In [39]:
arr5 = np.diag((3,4,5))
# print(arr5)

arr6 = np.eye((3), dtype= np.int64)
print(arr6)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


### dictionary

In [52]:
dit = { 
    'a' : 4,
    'b' : 5,
    'c' : 8,
    'e' : 6
}

arr_val = np.array(list(dit.values()))
print(arr_val)

arr_key = np.array(list(dit.keys()))
print(arr_key)

[4 5 8 6]
['a' 'b' 'c' 'e']


#### array with random value

In [58]:
arr = np.random.rand(2,3)
print(arr)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

[[0.65833114 0.19343248 0.10092614]
 [0.40434154 0.99374966 0.05241485]]
(2, 3)
6
float64
2


In [132]:
arr = np.random.randint(1,10,(3,3,2))
print(arr)

[[[7 8]
  [3 3]
  [2 5]]

 [[4 2]
  [7 5]
  [3 9]]

 [[7 6]
  [5 6]
  [5 1]]]


In [ ]:
                               #shape, row, column
arr = np.random.uniform(40,80, (3,2,3))
print(arr)

[[[40.18450574 50.75432037 51.50925372]
  [56.42174553 73.1629177  64.05126707]]

 [[49.98284407 40.62518509 71.19984746]
  [55.02770246 57.43041112 57.15724796]]

 [[54.52689048 59.47787538 70.12102733]
  [70.54056306 60.37156179 40.31174865]]]


#### array creation with range functions

In [ ]:
# np.random.uniform(start,end, shape) 
arr = np.arange(1,10, 1)
mat = arr.reshape(3,3)
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [147]:
arr = np.linspace(1,6 , 10)
print(arr)

arr1 = np.logspace(1,6 , 4)
print(arr1)

[1.         1.55555556 2.11111111 2.66666667 3.22222222 3.77777778
 4.33333333 4.88888889 5.44444444 6.        ]
[1.00000000e+01 4.64158883e+02 2.15443469e+04 1.00000000e+06]


### indexing and slicing

In [7]:
arr = np.array([1,2,3,4])

print(arr[2])

arr1 = np.array([[1,2,3],[2,3,5]])
print(arr1[1][2])

3
5


In [11]:
# slicing
arr_mod = arr[2:]
print(arr_mod)

[3 4]


In [16]:
arr1_mod = arr1[0:2,0:2]
print(arr1_mod)

[[1 2]
 [2 3]]


In [17]:
print(np.sin(np.pi/2))

1.0


[[19 22]
 [43 50]]
