In [2]:
import numpy as np

### Flatten colum or row wise

In [9]:
arr = np.random.randint(1,100, (4,5))
print(arr)
falten_arr = np.ravel(arr, order='A')
print(falten_arr)

[[75 61 44 25 93]
 [60 71 23  1 62]
 [20 78 48 21 75]
 [86 64 91 30 48]]
[75 61 44 25 93 60 71 23  1 62 20 78 48 21 75 86 64 91 30 48]


### concanate

In [18]:
a = np.random.randint(1,11,(2,3))
b = np.random.randint(1,11, (2,3))
print(a)
print(b)

concatenate = np.concat((a,b), axis=1)

print(concatenate)

[[10  4  3]
 [ 2  4  7]]
[[ 8  4  3]
 [ 6  8 10]]
[[10  4  3  8  4  3]
 [ 2  4  7  6  8 10]]


In [21]:
# transpose matrix

mat = np.random.randint(1,11, (2,3))

print(mat.T.shape)
mat.shape

(3, 2)


(2, 3)

### search array

In [25]:
arr = np.array([[1,2,3,4],
                [3,5,6,7]])

index = np.where(arr==10)
print(index)

(array([], dtype=int64), array([], dtype=int64))


### count array

In [34]:
arr = np.random.randint(1,100,(100,))
print(arr)

count_number = np.count_nonzero(arr<40)
# print(count_number)

unique_value = np.unique(arr, return_counts=True)
print(unique_value)

[ 4 25 13 66 49  6 21 50 82 14 62 86 62 25 92 70 76 29 10 48 56  7  2 61
 55 96 21  1 43 94 45  3 31  3 91 77 67 70 64 83 65 81  3 75 28 42 83 29
 88 66 73 91 71 39  7 30  8  1 97 11 50 81 27 75 51  5 82 42  5 55 62 13
 81 69 84 17 99 39 19 70 45 53 29 62 11 93 60 14 97 70 77 10 79 97 42  1
 73 69 85 46]
(array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11, 13, 14, 17, 19, 21, 25, 27,
       28, 29, 30, 31, 39, 42, 43, 45, 46, 48, 49, 50, 51, 53, 55, 56, 60,
       61, 62, 64, 65, 66, 67, 69, 70, 71, 73, 75, 76, 77, 79, 81, 82, 83,
       84, 85, 86, 88, 91, 92, 93, 94, 96, 97, 99], dtype=int32), array([3, 1, 3, 1, 2, 1, 2, 1, 2, 2, 2, 2, 1, 1, 2, 2, 1, 1, 3, 1, 1, 2,
       3, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 4, 1, 1, 2, 1, 2, 4, 1, 2,
       2, 1, 2, 1, 3, 2, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 3, 1]))
