1. Student Marks Analyzer
You are helping a teacher check exam results.
 Create a NumPy array with 10 random integers between 0 and 100 (student scores).

 Find:
 - the highest score
 - the lowest score
 - the average score

In [1]:
import numpy as np

In [10]:
arr = np.random.randint(0,100, 10)
print('Highest score: ',arr.max())
print('Lowest score: ',arr.min())
print('Average score: ',arr.mean())


Highest score:  98
Lowest score:  18
Average score:  53.2


A warehouse stores item weights (in kg):
 arr = np.array([45, 60, 55, 30, 90, 75, 40, 50])

 Find and print:
 - all items heavier than 50 kg
 - the sorted weights
 - the index of the heaviest item

In [ ]:
arr = np.array([45, 60, 55, 30, 90, 75, 40, 50])

heavier = arr[arr>50]
print(heavier)
print(np.sort(arr))
print(arr.argmax())

[60 55 90 75]
[30 40 45 50 55 60 75 90]
2


3. Temperature Report
A weather station collects temperatures (°C) from 4 zones.
 Generate random integers between 20 and 40 for a 4×4 grid.

 Then find:
 - the average temperature of each zone (row)
 - the highest temperature in the grid
 - replace all temperatures above 35 with 35

In [3]:
temperature = np.random.randint(20,40, (4,4))
print(temperature)

[[39 29 23 21]
 [22 33 29 38]
 [37 35 22 22]
 [24 20 28 31]]


In [7]:
print(temperature[0].mean())
print(temperature[1].mean())
print(temperature[2].mean())
print(temperature[3].mean())

28.0
30.5
29.0
25.75


In [8]:
print('Highest temperature in grid: ',temperature.mean())

Highest temperature in grid:  28.3125


In [11]:
temperature[temperature>35] = 35
temperature

array([[35, 29, 23, 21],
       [22, 33, 29, 35],
       [35, 35, 22, 22],
       [24, 20, 28, 31]], dtype=int32)

4. Traffic Data
A city records the number of cars passing 5 intersections in 3 time slots (morning, afternoon, night).
 Create a 3×5 array of random integers between 0 and 50.

 Then find:
 - total cars per intersection (sum by column)
 - total cars per time slot (sum by row)

In [12]:
A = np.random.randint(0,50,(3,5))
print(A)

[[44 36 27 18  4]
 [29  3 33 32 36]
 [24 20  8 18 30]]


In [18]:
print(A[:,0].sum())
print(A[:,1].sum())
print(A[:,2].sum())
print(A[:,3].sum())
print(A[:,4].sum())

97
59
68
68
70


In [19]:
print(A[0].sum())
print(A[1].sum())
print(A[2].sum())

129
133
100


In [21]:
A.sum(axis=0)
A.sum(axis=1)

array([129, 133, 100])

5. Fruit Store Stock
You sell fruits in your store. Stock levels (kg) for 5 days are:
 stock = np.array([12, 15, 9, 20, 18])

 A new delivery adds 5 kg to each stock.
 Then 10% of all fruits get spoiled.

 Find the final stock levels.

 Hint: use broadcasting and simple math.

In [4]:
stock = np.array([12,15,9,20,18])

stock = (stock + 5)
stock_spoiled = stock * .1
final_stock = stock - stock_spoiled
print(final_stock)

[15.3 18.  12.6 22.5 20.7]


1. Student Report Analyzer
You are given this data:

 import pandas as pd

 data = {
 	'Name': ['Rahim', 'Karim', 'Selina', 'Babul', 'Mitu'],
 	'Math': [88, 75, 95, 60, 80],
 	'English': [78, 85, 90, 70, 88],
 	'Science': [92, 70, 85, 65, 90]
 }
 df = pd.DataFrame(data)

 Tasks:
 1. Display only the first 3 rows.
 2. Print the column names and index values.

In [5]:
import pandas as pd

data = {
    'Name': ['Rahim', 'Karim', 'Selina', 'Babul', 'Mitu'],
    'Math': [88, 75, 95, 60, 80],
    'English': [78, 85, 90, 70, 88],
    'Science': [92, 70, 85, 65, 90]
}
df = pd.DataFrame(data)


In [6]:
print(df.head(3))

     Name  Math  English  Science
0   Rahim    88       78       92
1   Karim    75       85       70
2  Selina    95       90       85


In [11]:
print(df.columns)
print(df.index)

Index(['Name', 'Math', 'English', 'Science'], dtype='object')
RangeIndex(start=0, stop=5, step=1)


2. Shop Sales Data
You run a small electronics shop. The data is stored like this:

 data = {
 	'Product': ['Phone', 'Laptop', 'Tablet', 'Monitor', 'Mouse'],
 	'Price': [700, 1200, 300, 250, 50],
 	'Units_Sold': [10, 5, 8, 6, 20]
 }
 df = pd.DataFrame(data)

 Tasks:
 1. Display only the 'Product' and 'Price' columns.
 2. Access the 3rd row using both iloc and loc.
 3. Show the top 3 products with the highest revenue.

In [36]:
data = {
 	'Product': ['Phone', 'Laptop', 'Tablet', 'Monitor', 'Mouse'],
 	'Price': [700, 1200, 300, 250, 50],
 	'Units_Sold': [10, 5, 8, 6, 20]
}
df = pd.DataFrame(data)
df

Product  Price  Units_Sold
0    Phone    700          10
1   Laptop   1200           5
2   Tablet    300           8
3  Monitor    250           6
4    Mouse     50          20

In [37]:
df[['Product','Price']]

Product  Price
0    Phone    700
1   Laptop   1200
2   Tablet    300
3  Monitor    250
4    Mouse     50

In [38]:
df.loc[0:2]

Product  Price  Units_Sold
0   Phone    700          10
1  Laptop   1200           5
2  Tablet    300           8

In [39]:
df.iloc[0:2,0:3]

Product  Price  Units_Sold
0   Phone    700          10
1  Laptop   1200           5

In [44]:
df['Revenue'] = df['Price']*df['Units_Sold']
df.sort_values('Revenue',ascending=False).head(3)

Product  Price  Units_Sold  Revenue
0   Phone    700          10     7000
1  Laptop   1200           5     6000
2  Tablet    300           8     2400

In [46]:
df.sort_values('Revenue', ascending=False)
df[['Product','Revenue']].head(3)

Product  Revenue
0   Phone     7000
1  Laptop     6000
2  Tablet     2400

3. Attendance Tracker
Here’s an attendance sheet:

 data = {
 	'Student': ['Amin', 'Tina', 'Rafi', 'Nadia', 'Sabbir'],
 	'Days_Present': [20, 18, 22, 15, 25],
 	'Days_Absent': [2, 4, 1, 7, 0]
 }
 df = pd.DataFrame(data)

 Tasks:
 1. Make 'Student' the index column.
 2. Drop the 'Days_Absent' column.

In [47]:
data = {
 	'Student': ['Amin', 'Tina', 'Rafi', 'Nadia', 'Sabbir'],
 	'Days_Present': [20, 18, 22, 15, 25],
 	'Days_Absent': [2, 4, 1, 7, 0]
}
df = pd.DataFrame(data)


In [50]:
df.set_index('Student')

Days_Present  Days_Absent
Student                           
Amin               20            2
Tina               18            4
Rafi               22            1
Nadia              15            7
Sabbir             25            0

In [54]:
df.drop(columns='Days_Absent',inplace=True)
df

Student  Days_Present
0    Amin            20
1    Tina            18
2    Rafi            22
3   Nadia            15
4  Sabbir            25

4. Filtering Employee Data
Employee record:

 data = {
 	'Name': ['Rafiq', 'Nadia', 'Tuhin', 'Rima', 'Faruk'],
 	'Department': ['HR', 'IT', 'IT', 'Sales', 'Sales'],
 	'Salary': [40000, 55000, 52000, 45000, 47000],
 	'Experience': [2, 5, 4, 3, 6]
 }
 df = pd.DataFrame(data)

 Tasks:
 1. Show employees with Salary > 45000.
 2. Show employees from the IT department only.
 3. Show employees with Salary > 45000 and Experience > 3.
 4. Sort the employees by Experience (ascending).

In [55]:
data = {
 	'Name': ['Rafiq', 'Nadia', 'Tuhin', 'Rima', 'Faruk'],
 	'Department': ['HR', 'IT', 'IT', 'Sales', 'Sales'],
 	'Salary': [40000, 55000, 52000, 45000, 47000],
 	'Experience': [2, 5, 4, 3, 6]
 }
df = pd.DataFrame(data)

In [58]:
print(df[df['Salary']>45000])

    Name Department  Salary  Experience
1  Nadia         IT   55000           5
2  Tuhin         IT   52000           4
4  Faruk      Sales   47000           6


In [59]:
print(df[df['Department']=='IT'])

    Name Department  Salary  Experience
1  Nadia         IT   55000           5
2  Tuhin         IT   52000           4


In [69]:
print(df[(df['Salary']>45000) & (df['Experience']>3)])

    Name Department  Salary  Experience
1  Nadia         IT   55000           5
2  Tuhin         IT   52000           4
4  Faruk      Sales   47000           6


In [70]:
print(df.sort_values('Experience'))

    Name Department  Salary  Experience
0  Rafiq         HR   40000           2
3   Rima      Sales   45000           3
2  Tuhin         IT   52000           4
1  Nadia         IT   55000           5
4  Faruk      Sales   47000           6


5. City Weather Dashboard
data = {
 	'City': ['Dhaka', 'Sylhet', 'Chittagong', 'Rajshahi', 'Khulna'],
 	'Temp': [32, 28, 30, 35, 33],
 	'Humidity': [60, 75, 70, 55, 65]
 }
 df = pd.DataFrame(data)

 Tasks:
 1. Show only the cities where FeelsLike > 33.
 2. Sort the DataFrame by FeelsLike (descending).
 3. Find which city has the highest humidity.

In [85]:

data = {
 	'City': ['Dhaka', 'Sylhet', 'Chittagong', 'Rajshahi', 'Khulna'],
 	'Temp': [32, 28, 30, 35, 33],
 	'Humidity': [60, 75, 70, 55, 65]
}
df = pd.DataFrame(data)


In [86]:
print(df['City'][df['Temp']>33])

3    Rajshahi
Name: City, dtype: object


In [87]:
df.sort_values('Temp',ascending=False)

City  Temp  Humidity
3    Rajshahi    35        55
4      Khulna    33        65
0       Dhaka    32        60
2  Chittagong    30        70
1      Sylhet    28        75

In [94]:
df['City'][df['Humidity'] == df['Humidity'].max()]

1    Sylhet
Name: City, dtype: object

In [3]:
import pandas as pd
import numpy as np

In [34]:

data = {
    'account_id': [3,2,8,6],
    'income' : [108939,12747,87709,91796]
}

In [35]:
accounts = pd.DataFrame(data)

In [36]:
Low = accounts['income'][accounts['income']<20000].count()
avg = accounts['income'][(accounts['income']>=20000) & (accounts['income']<=50000)].count()
high = accounts['income'][accounts['income']>50000].count()


In [37]:
data = {
    'category':['Low Salary','Average Salary','High Salary'],
    'accounts_count': [Low,avg,high]
}
df = pd.DataFrame(data)
df

category  accounts_count
0      Low Salary               1
1  Average Salary               0
2     High Salary               3

In [39]:
data = {
    'id':[1,2,3],
    'email':['john@example.com','bob@example.com','bob@example.com']
}
df = pd.DataFrame(data)
df

id             email
0   1  john@example.com
1   2   bob@example.com
2   3   bob@example.com

In [ ]:
df.drop_duplicates(subset=['email'],keep='first',inplace=True)

id             email
0   1  john@example.com
1   2   bob@example.com