In [1]:
import numpy as np

### 1 . Create a 1D, 2D, and 3D NumPy array and print their dimensions and shapes.

In [9]:
arr_1d = np.array([1,2,3])
arr_2d = np.array([[1,2,3], 
                   [4,5,6]])
arr_3d = np.array([[[1,2,3],
                   [4,5,6],
                   [7,8,9],[1,2,3],
                   [4,5,6],
                   [7,8,9]]])

print(arr_1d)
print(arr_1d.ndim)
print(arr_1d.shape)

print(arr_2d)
print(arr_2d.ndim)
print(arr_2d.shape)

print(arr_3d)
print(arr_3d.ndim)
print(arr_3d.shape)

[1 2 3]
1
(3,)
[[1 2 3]
 [4 5 6]]
2
(2, 3)
[[[1 2 3]
  [4 5 6]
  [7 8 9]
  [1 2 3]
  [4 5 6]
  [7 8 9]]]
3
(1, 6, 3)


### 2 . Create:
an array of zeros of shape (3,3)


an array of ones of shape (2,5)


an array filled with 7


In [16]:
arr_zero = np.zeros((3,3))
arr_one = np.ones((2,5))

print(arr_zero)
print(arr_one)

arr_fill = np.full(5,7)
arr_fill_3D = np.full((3,4,2),7) 
print(arr_fill_3D)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[[7 7]
  [7 7]
  [7 7]
  [7 7]]

 [[7 7]
  [7 7]
  [7 7]
  [7 7]]

 [[7 7]
  [7 7]
  [7 7]
  [7 7]]]


### Create an array of even numbers between 10 and 50 using arange.

In [20]:
arr_even = np.arange(10,50, 2)
print(arr_even)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


### 4 . Create a 4×4 matrix from 0–15. Then , extract:
the first row


the last column


a 2×2 subarray from the center


In [28]:
arr = np.random.randint(0,15,(4,4))

print(arr)
print(arr[0:1,::])
print(arr[::,2:4])
print(arr[1:3,1:3])

[[ 3  9  8  9]
 [ 6  3 14  6]
 [11 13  4  1]
 [ 8  5  8  7]]
[[3 9 8 9]]
[[ 8  9]
 [14  6]
 [ 4  1]
 [ 8  7]]
[[ 3 14]
 [13  4]]


### 5 . Add a 1D array [1,2,3] to each row of a 3×3 matrix.

In [ ]:
arr = np.random.randint(0,10,(3,3))
arr1 = np.array([1,2,3])
arr3 = ((arr+arr1))
print(arr)
print(arr3)

[[8 0 9]
 [1 8 3]
 [5 2 4]]
[[ 9  2 12]
 [ 2 10  6]
 [ 6  4  7]]


### 6 . Given two arrays A and B, compute:
(A + B) / 2


A**2 + B**2


In [35]:
A = np.random.randint(0,10,(2,2))
B = np.random.randint(0,10,(2,2))
print(A)
print(B)
print((A + B)/2)
print(A**2 + B**2)

[[0 8]
 [9 7]]
[[4 2]
 [7 8]]
[[2.  5. ]
 [8.  7.5]]
[[ 16  68]
 [130 113]]


In [15]:
arr = np.random.randint(1,20, (5,5))
print(arr)
print(arr[0])
print(arr[1:5,0])
print(arr[1:5,-1])
print(arr[-1])

arr2 = np.concatenate((arr[0],arr[1:5,0],arr[1:5,-1],arr[-1]))
print(arr2)

[[14 10 14 19 18]
 [15 19  1 12 13]
 [ 5 16  8  8 12]
 [19  4  7 14  9]
 [ 5 14 13  2  6]]
[14 10 14 19 18]
[15  5 19  5]
[13 12  9  6]
[ 5 14 13  2  6]
[14 10 14 19 18 15  5 19  5 13 12  9  6  5 14 13  2  6]


In [16]:
arr = np.random.randint(1,10, (4,4))
print(arr)

[[9 2 3 9]
 [2 4 2 6]
 [7 9 8 4]
 [7 9 1 2]]


In [18]:
row_sum = np.sum(arr, axis=1)
print(row_sum)
col_sum = np.sum(arr, axis=0)
print(col_sum)

[23 14 28 19]
[25 24 14 21]


In [ ]:
np.diago